apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER willy WITH PASSWORD 'admin';
      CREATE DATABASE puentedb;
      GRANT ALL PRIVILEGES ON DATABASE puentedb TO willy;
    EOSQL
