apiVersion: v1
kind: Secret #Con esto el sistema sabe que la  data esta codificada
metadata:
  name: postgres-secret
  labels:
    app: postgres
    #meant that we can use arbitrary key pair values
type: Opaque 
#? esto indica que colocaremos datos arbitrarios
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
