#? configurano el servicio de pgadmin
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  #type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      nodePort: 30200
